let
  Root      = AzureStorage.DataLake("https://goodreadsreviews60106541.dfs.core.windows.net", [HierarchicalNavigation=true]),
  Lakehouse = Root{[Name="lakehouse"]}[Content],
  Gold      = Lakehouse{[Name="gold"]}[Content],
  Curated   = Gold{[Name="curated_reviews_delta"]}[Content],
  Delta     = DeltaLake.Table(Curated),
  #"Changed column type" = Table.TransformColumnTypes(Delta, {{"book_id", Int64.Type}, {"author_id", Int64.Type}}),
  #"Trimmed text" = Table.TransformColumns(#"Changed column type", {{"title", each Text.Trim(_), type nullable text}}),
  #"Trimmed text 1" = Table.TransformColumns(#"Trimmed text", {{"review_text", each Text.Trim(_), type nullable text}}),
  #"Trimmed text 2" = Table.TransformColumns(#"Trimmed text 1", {{"language", each Text.Trim(_), type nullable text}}),
  #"Cleaned text" = Table.TransformColumns(#"Trimmed text 2", {{"language", each Text.Clean(_), type nullable text}}),
  #"Cleaned text 1" = Table.TransformColumns(#"Cleaned text", {{"review_text", each Text.Clean(_), type nullable text}}),
  #"Cleaned text 2" = Table.TransformColumns(#"Cleaned text 1", {{"title", each Text.Clean(_), type nullable text}}),
  #"Removed blank rows" = Table.SelectRows(#"Cleaned text 2", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
  #"Added custom" = Table.AddColumn(#"Removed blank rows", "review_length", each Text.Length([review_text])),
  #"Filtered rows" = Table.SelectRows(#"Added custom", each [review_length] >= 10),
  #"Removed blank rows 1" = Table.SelectRows(#"Filtered rows", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
  #"Filtered rows 1" = Table.SelectRows(#"Removed blank rows 1", each ([date_added] <> null)),
  #"Replaced value" = Table.ReplaceValue(#"Filtered rows 1", null, 0, Replacer.ReplaceValue, {"n_votes"}),
  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", null, "Unknown", Replacer.ReplaceValue, {"language"}),
  #"Trimmed text 3" = Table.TransformColumns(#"Replaced value 1", {{"review_text", each Text.Trim(_), type nullable text}}),
  #"Trimmed text 4" = Table.TransformColumns(#"Trimmed text 3", {{"name", each Text.Trim(_), type nullable text}}),
  #"Trimmed text 5" = Table.TransformColumns(#"Trimmed text 4", {{"title", each Text.Trim(_), type nullable text}}),
  #"Capitalized each word" = Table.TransformColumns(#"Trimmed text 5", {{"title", each Text.Proper(_), type nullable text}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Capitalized each word", {{"rating", Int64.Type}}),
  #"Removed errors" = Table.RemoveRowsWithErrors(#"Changed column type 1", {"rating"}),
  #"Removed blank rows 2" = Table.SelectRows(#"Removed errors", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Removed blank rows 2", {{"rating", type number}}),
  #"Removed errors 1" = Table.RemoveRowsWithErrors(#"Changed column type 2", {"book_id"}),
  #"Removed errors 2" = Table.RemoveRowsWithErrors(#"Removed errors 1", {"review_id"})
in
  #"Removed errors 2"